name: lipyphilic
channels:
    - conda-forge
    - defaults
dependencies:
    - python >=3.7
    - numpy >=1.16
    - scipy >=1.5
    - pandas >=1.1.0
    - mdanalysis >=1.0
    - freud >=2.4.1
    - tidynamics
    - seaborn>=0.11
    - tqdm
    - pip
    - pip:
        - lipyphilic
